name: Taiwan_credit_card_default
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - xgboost
    - mlflow
    - shap
    - joblib  



    with open('environment.yml', 'w') as f:
    yaml.dump(environment_dict, f)

print("âœ… environment.yml created!")

# Now your MLflow code will work
with mlflow.start_run(run_name="xgboost_with_created_env"):
    mlflow.xgboost.log_model(
        xgb_model=model_xgboost,
        artifact_path="xgboost_model",
        conda_env="environment.yml",  # Now this file exists
        signature=mlflow.models.signature.infer_signature(X_train1, y_pred)
    )